### ISSUE TITLE
var defaultWebHost = "http://129.211.98.114:3006" - IP located in China - major issue 

### ISSUE THREAD

**Issue by Bambarello** [sero-cash/pullup#1]
Please consider changing the default webhost to the EU location, as this IP is located in China and Pullup wallet is not working for the number of countries.

One of issues - the account can't be created.

**Comment by gordon-sero** [comment]
@Bambarello currently we add the japaness node to the pullup wallet, you could use the v0.1.4

https://github.com/sero-cash/pullup/releases/tag/v0.1.4

**Comment by Bambarello** [comment]
Thanks Gordon for keeping an eye on all the things!
Is the failover to the secondary node automatic or shall we somehow modify the pullup wallet start script?

**Comment by tomdurrent** [comment]
1. v0.1.5 uses Japanese server nodes by default. Default config:
>- defaultRpcHost = "http://52.199.145.159:8545"
>- defaultWebHost = "http://pullup.sero.cash/v0_1_5/"

2. You can also open the web's static assets using the protocol of the file, or deploy it on your own server, and then use the browser to access the web static assets. And start the pullup service server on the computer.

3. If you are using source code compilation, you can add the following parameters to the startup parameters:
> --rpcHost `replace your gero node server`
> --webHost `replace your static assets server`

**This way to start, you need to configure environment variables
DYLD_LIBRARY_PATH="github.com/sero-cash/go-czero-import/czero/lib"**

Above, I hope to help you.

**Comment by Bambarello** [comment]
Thank you, this seems working. If possible, please advise how to run pullup.exe (in windows) with the RPCHost parameter (to select either China or Japan server)
